const SIGNOUT = "SIGNOUT";
const RESTORE = "RESTORE";
const SIGNUP_REQUESTED = "SIGNUP_REQUESTED";
const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
const SIGNIN_SIGNUP_SUCCEEDED = "SIGNIN_SIGNUP_SUCCEEDED";
const SIGNIN_SIGNUP_FAILED = "SIGNIN_SIGNUP_FAILED";

const CONSTANTS = {
  SIGNOUT,
  RESTORE,
  SIGNUP_REQUESTED,
  SIGNIN_REQUESTED,
  SIGNIN_SIGNUP_SUCCEEDED,
  SIGNIN_SIGNUP_FAILED,
};

export default CONSTANTS;
