const COLLECTION_SET = "COLLECTION_SET";
const COLLECTIONS_FETCH_REQUESTED = "COLLECTIONS_FETCH_REQUESTED";
const COLLECTIONS_FETCH_SUCCEEDED = "COLLECTIONS_FETCH_SUCCEEDED";
const COLLECTIONS_FETCH_FAILED = "COLLECTIONS_FETCH_FAILED";
const COLLECTIONS_REORDER_REQUESTED = "COLLECTIONS_REORDER_REQUESTED";
const COLLECTIONS_REORDER_DRAFT = "COLLECTIONS_REORDER_DRAFT";
const COLLECTIONS_REORDER_SUCCEEDED = "COLLECTIONS_REORDER_SUCCEEDED";
const COLLECTIONS_REORDER_FAILED = "COLLECTIONS_REORDER_FAILED";
const COLLECTION_POST_REQUESTED = "COLLECTION_POST_REQUESTED";
const COLLECTION_POST_SUCCEEDED = "COLLECTION_POST_SUCCEEDED";
const COLLECTION_POST_FAILED = "COLLECTION_POST_FAILED";
const COLLECTION_DELETE_REQUESTED = "COLLECTION_DELETE_REQUESTED";
const COLLECTION_DELETE_SUCCEEDED = "COLLECTION_DELETE_SUCCEEDED";
const COLLECTION_DELETE_FAILED = "COLLECTION_DELETE_FAILED";
const COLLECTION_ADD_PLACE_REQUESTED = "COLLECTION_ADD_PLACE_REQUESTED";
const COLLECTION_ADD_PLACE_SUCCEEDED = "COLLECTION_ADD_PLACE_SUCCEEDED";
const COLLECTION_ADD_PLACE_FAILED = "COLLECTION_ADD_PLACE_FAILED";
const COLLECTION_DELETE_PLACE_REQUESTED = "COLLECTION_DELETE_PLACE_REQUESTED";
const COLLECTION_DELETE_PLACE_SUCCEEDED = "COLLECTION_DELETE_PLACE_SUCCEEDED";
const COLLECTION_DELETE_PLACE_FAILED = "COLLECTION_DELETE_PLACE_FAILED";

const CONSTANTS = {
  COLLECTION_SET,
  COLLECTIONS_FETCH_REQUESTED,
  COLLECTIONS_FETCH_SUCCEEDED,
  COLLECTIONS_FETCH_FAILED,
  COLLECTIONS_REORDER_REQUESTED,
  COLLECTIONS_REORDER_DRAFT,
  COLLECTIONS_REORDER_SUCCEEDED,
  COLLECTIONS_REORDER_FAILED,
  COLLECTION_POST_REQUESTED,
  COLLECTION_POST_SUCCEEDED,
  COLLECTION_POST_FAILED,
  COLLECTION_DELETE_REQUESTED,
  COLLECTION_DELETE_SUCCEEDED,
  COLLECTION_DELETE_FAILED,
  COLLECTION_ADD_PLACE_REQUESTED,
  COLLECTION_ADD_PLACE_SUCCEEDED,
  COLLECTION_ADD_PLACE_FAILED,
  COLLECTION_DELETE_PLACE_REQUESTED,
  COLLECTION_DELETE_PLACE_SUCCEEDED,
  COLLECTION_DELETE_PLACE_FAILED,
};

export default CONSTANTS;
