const COLLECTIONS_FETCH_REQUESTED = "COLLECTIONS_FETCH_REQUESTED";
const COLLECTIONS_FETCH_SUCCEEDED = "COLLECTIONS_FETCH_SUCCEEDED";
const COLLECTIONS_FETCH_FAILED = "COLLECTIONS_FETCH_FAILED";
const COLLECTION_POST_REQUESTED = "COLLECTION_POST_REQUESTED";
const COLLECTION_POST_SUCCEEDED = "COLLECTION_POST_SUCCEEDED";
const COLLECTION_POST_FAILED = "COLLECTION_POST_FAILED";
const COLLECTION_DELETE_REQUESTED = "COLLECTION_DELETE_REQUESTED";
const COLLECTION_DELETE_SUCCEEDED = "COLLECTION_DELETE_SUCCEEDED";
const COLLECTION_DELETE_FAILED = "COLLECTION_DELETE_FAILED";
const COLLECTIONS_QUERIED = "COLLECTIONS_QUERIED";

const CONSTANTS = {
  COLLECTIONS_FETCH_REQUESTED,
  COLLECTIONS_FETCH_SUCCEEDED,
  COLLECTIONS_FETCH_FAILED,
  COLLECTION_POST_REQUESTED,
  COLLECTION_POST_SUCCEEDED,
  COLLECTION_POST_FAILED,
  COLLECTION_DELETE_REQUESTED,
  COLLECTION_DELETE_SUCCEEDED,
  COLLECTION_DELETE_FAILED,
  COLLECTIONS_QUERIED,
};

export default CONSTANTS;
