const COLLECTIONS_FETCH_REQUESTED = "COLLECTIONS_FETCH_REQUESTED";
const COLLECTIONS_FETCH_SUCCEEDED = "COLLECTIONS_FETCH_SUCCEEDED";
const COLLECTIONS_FETCH_FAILED = "COLLECTIONS_FETCH_FAILED";
const COLLECTIONS_QUERIED = "COLLECTIONS_QUERIED";

const CONSTANTS = {
  COLLECTIONS_FETCH_REQUESTED,
  COLLECTIONS_FETCH_SUCCEEDED,
  COLLECTIONS_FETCH_FAILED,
  COLLECTIONS_QUERIED,
};

export default CONSTANTS;
