const LOCATIONS_FETCH_REQUESTED = "LOCATIONS_FETCH_REQUESTED";
const LOCATIONS_FETCH_SUCCEEDED = "LOCATIONS_FETCH_SUCCEEDED";
const LOCATIONS_FETCH_FAILED = "LOCATIONS_FETCH_FAILED";
const LOCATIONS_SELECTED = "LOCATIONS_SELECTED";
const LOCATIONS_QUERIED = "LOCATIONS_QUERIED";

const CONSTANTS = {
  LOCATIONS_FETCH_REQUESTED,
  LOCATIONS_FETCH_SUCCEEDED,
  LOCATIONS_FETCH_FAILED,
  LOCATIONS_SELECTED,
  LOCATIONS_QUERIED,
};

export default CONSTANTS;
