const TOWNS_FETCH_REQUESTED = "TOWNS_FETCH_REQUESTED";
const TOWNS_FETCH_SUCCEEDED = "TOWNS_FETCH_SUCCEEDED";
const TOWNS_FETCH_FAILED = "TOWNS_FETCH_FAILED";
const TOWNS_SELECTED = "TOWNS_SELECTED";
const TOWNS_QUERIED = "TOWNS_QUERIED";

const CONSTANTS = {
  TOWNS_FETCH_REQUESTED,
  TOWNS_FETCH_SUCCEEDED,
  TOWNS_FETCH_FAILED,
  TOWNS_SELECTED,
  TOWNS_QUERIED,
};

export default CONSTANTS;
